### ISSUE TITLE
route

### ISSUE THREAD

**Issue by farshidpc** [tohidplus/mellat#1]
سلام
روت هاش رو مشخص می کنید چون موقع برگشت از بانک خطای 
The POST method is not supported for route paypalverify. Supported methods: GET, HEAD.
میگیرم

**Comment by tohidplus** [comment]
Hello @farshidpc 

Seems like the route you have defined (papalverifry) for handling the callback URL only supports the GET, and HEAD methods. 
You should change the accepted HTTP method for your route.

Here is an example:
```php
Route::post('/paypalverify', [VerifyPaymentController::class, 'verify']);
```

Hope it helps to solve your problem
